apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-rqxvkfuy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-rqxvkfuy:980c3293310e9a9fb31223b2f49fb6e8da3d3452@sha256:2e624bd784fdfc2dbf4b5836db2e553a9dd7708ef3a000bdc9371c7a2076e28a
          name: container-image
